---

  - name: Add Redis Repo into source list
    apt_repository:
      repo: 'ppa:chris-lea/redis-server'
      state: present
      update_cache: yes

  - name: Install Redis server
    apt:
      name: redis-server
      state: present

  - name: Configure Redis server
    template:
      src: redis.conf.j2
      dest: /etc/redis/redis.conf
      force: yes 

  - name: Restart Redis server
    service: 
      name: redis-server
      state: restarted

  - name: Create Feature Flag (Default off)
    command: redis-cli set mdFlag false


